# Generated by Django 5.1 on 2024-08-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemamg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_img',
            field=models.ImageField(blank=True, null=True, upload_to='cinemamg/%Y/%m/'),
        ),
    ]
