# Generated by Django 5.1 on 2024-08-31 13:34

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemamg', '0003_movie_trailer_url_alter_movie_poster_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seats',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_img',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
