# Generated by Django 5.1 on 2024-08-31 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemamg', '0004_alter_booking_seats_alter_movie_poster_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='start',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='invoice',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinemamg.promotion'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.DecimalField(decimal_places=3, default=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='final_amount',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
