# Generated by Django 5.1 on 2024-08-31 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemamg', '0006_alter_promotion_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='discount',
        ),
    ]
