# Generated by Django 5.1 on 2024-08-31 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemamg', '0007_remove_invoice_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='promotion',
        ),
        migrations.AddField(
            model_name='booking',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinemamg.promotion'),
        ),
    ]
