# Generated by Django 5.1 on 2024-08-31 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemamg', '0008_remove_invoice_promotion_booking_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinemamg.promotion'),
        ),
    ]
