# Generated by Django 5.1 on 2024-08-31 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemamg', '0010_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster_img',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
